'use client';

import RecommendationsList from './RecommendationsList';

export default function ChatMessage({ message }) {
    const isAssistant = message.role === 'assistant';

    // Clean up formatting: maintain line breaks and handle bold markers if any
    const formatContent = (content) => {
        return content.split('\n').map((line, i) => (
            <span key={i} className="block mb-2 last:mb-0">
                {line}
            </span>
        ));
    };

    return (
        <div className={`flex w-full ${isAssistant ? 'justify-start' : 'justify-end'} animate-in fade-in slide-in-from-bottom-2 duration-300 group`}>
            <div className={`flex items-start max-w-[92%] md:max-w-[85%] space-x-3 md:space-x-4 ${isAssistant ? 'flex-row' : 'flex-row-reverse space-x-reverse'}`}>

                {/* Avatar with Status Ring */}
                <div className="relative flex-shrink-0">
                    <div className={`w-10 h-10 rounded-2xl flex items-center justify-center shadow-lg transform transition-transform group-hover:scale-110 ${isAssistant
                            ? 'bg-gradient-to-tr from-indigo-600 to-violet-500 text-white'
                            : 'bg-white border-2 border-indigo-100 text-indigo-600'
                        }`}>
                        <span className="text-xl">
                            {isAssistant ? '✨' : '👤'}
                        </span>
                    </div>
                    {isAssistant && (
                        <div className="absolute -bottom-1 -right-1 w-4 h-4 bg-white rounded-full flex items-center justify-center shadow-sm">
                            <div className="w-2.5 h-2.5 bg-green-500 rounded-full animate-pulse"></div>
                        </div>
                    )}
                </div>

                {/* Message Container */}
                <div className={`flex flex-col ${isAssistant ? 'items-start' : 'items-end'} space-y-2`}>
                    {/* Label */}
                    <span className="px-2 text-[10px] font-black uppercase tracking-widest text-gray-400">
                        {isAssistant ? 'FinChat AI Advisor' : 'You'}
                    </span>

                    {/* Bubble */}
                    <div className={`relative px-6 py-4 rounded-3xl shadow-sm transition-all ${isAssistant
                            ? 'bg-white/80 backdrop-blur-md border border-white text-gray-800 rounded-tl-none chat-bubble-shadow ring-1 ring-black/[0.02]'
                            : 'bg-indigo-600 text-white rounded-tr-none shadow-indigo-100'
                        }`}>
                        <div className={`text-sm md:text-[15px] leading-relaxed font-medium whitespace-pre-wrap`}>
                            {message.content}
                        </div>

                        {/* Decoration for Assistant */}
                        {isAssistant && (
                            <div className="absolute top-0 right-0 p-2 opacity-10 pointer-events-none">
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
                                    <path d="M12 2L14.4 7.2L20 8L16 12L16.9 17.6L12 15L7.1 17.6L8 12L4 8L9.6 7.2L12 2Z" />
                                </svg>
                            </div>
                        )}
                    </div>

                    {/* Inline recommendations with distinct spacing */}
                    {isAssistant && message.recommendations && message.recommendations.length > 0 && (
                        <div className="w-full mt-6 space-y-8 animate-in fade-in duration-1000 slide-in-from-bottom-4">
                            <div className="flex items-center space-x-4 px-2">
                                <div className="h-[1px] flex-grow bg-gradient-to-r from-transparent via-indigo-100 to-transparent"></div>
                                <div className="flex items-center space-x-2">
                                    <span className="text-xs font-black text-indigo-400 uppercase tracking-[0.3em]">Portfolio Analysis</span>
                                </div>
                                <div className="h-[1px] flex-grow bg-gradient-to-r from-transparent via-indigo-100 to-transparent"></div>
                            </div>

                            <RecommendationsList recommendations={message.recommendations} />

                            <div className="flex justify-center pt-2">
                                <div className="px-4 py-2 bg-indigo-50/50 rounded-full border border-indigo-100/50">
                                    <p className="text-[10px] font-bold text-indigo-500 uppercase tracking-tighter">
                                        Generated by FinChat AI Intelligence Engine
                                    </p>
                                </div>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
